### ISSUE TITLE
Dailies which are for certain specific day are also active on the other days

### ISSUE THREAD

**Issue by drashwinrajeev** [HabitRPG/habitrpg-mobile#336] opened 2015-01-28 11:11 UTC
The dailies section in the HabitRPG app for iOS in my iPad shows a checkbox for the days it's **NOT** scheduled for.

**Comment by paglias** [comment] 2015-01-28 16:01
@drashwinrajeev thanks for the report. Is this happening only on the mobile app? The site is ok? Also, ae you using Android or iOS?

**Comment by crookedneighbor** [comment] 2015-01-28 16:11
This is what my daily for watering the plant on my desk looks like, I water it on Tuesday. Is it different from how yours looks? If so, please attach a screenshot (you will be unable to do it through email, you'll have to log into Github and drag it onto your comment)

![img_8088](https://cloud.githubusercontent.com/assets/2916945/5941305/b7780734-a6d5-11e4-8d37-f6d7ee0d3ff0.png)

The idea is that the buttons are "pushed in" to show they are active. Again, if you're seeing something totally different, please post a screenshot (power button and home button at the same time).

**Comment by crookedneighbor** [comment] 2015-01-28 16:18
@drashwinrajeev I misunderstood your issue at first. Reading it over again, it looks like you're saying that your dailies are visible and able to be checked even if they are not due.

Are the not due dailies gray? If so, that's expected behavior. That will allow you to check off the daily and get points, but you won't be penalized for not doing them.

A good use case would be for exercising. Let's say you require yourself to exercise on Mondays and Wednesdays, but one week on Friday you end up going to the gym, even though you weren't required to. This allows you to still get points for doing that.

**Comment by crookedneighbor** [comment] 2015-08-15 19:17
I'm closing this because we're actively working on native apps and this app will soon be deprecated. 

For iOS users, you [can download the app here](https://itunes.apple.com/us/app/habitica/id994882113?mt=8) and see the [source code here](https://github.com/HabitRPG/habitrpg-ios).

For Android users, we're finishing up the initial version and will release it soon. I will post [here when it is ready](https://github.com/HabitRPG/habitrpg-mobile/issues/385)

**Closed by crookedneighbor** 2015-08-15 19:17 UTC
