### ISSUE TITLE
Unable to close image detail view from Tavern image on iPhone app

### ISSUE THREAD

**Issue by AesteroidBlues** [HabitRPG/habitrpg-mobile#338] opened 2015-01-29 16:18 UTC
Repro steps:
-Go to the Tavern
-Click an image embedded in a post
-No way to close the image and return to the tavern  other than killing Habit RPG app and reopening.

Tested on iPhone 5 with iOS 8.1.3

**Comment by negue** [comment] 2015-01-29 23:19
Closing this as duplicate of #227 - and I just added the fix, it'll be available in the next App Update :)

**Closed by negue** 2015-01-29 23:19 UTC
